// Code generated by protoc-gen-go.
// source: applicant.proto
// DO NOT EDIT!

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	applicant.proto

It has these top-level messages:
	ApSignup
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApSignup struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Firstname string `protobuf:"bytes,2,opt,name=Firstname" json:"Firstname,omitempty"`
	Lastname  string `protobuf:"bytes,3,opt,name=Lastname" json:"Lastname,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=Password" json:"Password,omitempty"`
}

func (m *ApSignup) Reset()                    { *m = ApSignup{} }
func (m *ApSignup) String() string            { return proto.CompactTextString(m) }
func (*ApSignup) ProtoMessage()               {}
func (*ApSignup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApSignup) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ApSignup) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *ApSignup) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *ApSignup) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ApSignup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*ApSignup)(nil), "storage.ApSignup")
}

func init() { proto.RegisterFile("applicant.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x28, 0xc8,
	0xc9, 0x4c, 0x4e, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x2e, 0xc9,
	0x2f, 0x4a, 0x4c, 0x4f, 0x55, 0x6a, 0x63, 0xe4, 0xe2, 0x70, 0x2c, 0x08, 0xce, 0x4c, 0xcf, 0x2b,
	0x2d, 0x10, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2,
	0x74, 0x11, 0x92, 0xe1, 0xe2, 0x74, 0xcb, 0x2c, 0x2a, 0x2e, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x02, 0x0b, 0x23, 0x04, 0x84, 0xa4, 0xb8, 0x38, 0x7c, 0x12, 0xa1, 0x92, 0xcc, 0x60, 0x49, 0x38,
	0x5f, 0x48, 0x84, 0x8b, 0xd5, 0x35, 0x37, 0x31, 0x33, 0x47, 0x82, 0x05, 0x2c, 0x01, 0xe1, 0x80,
	0x74, 0x04, 0x24, 0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48, 0xb0, 0x42, 0x74, 0xc0, 0xf8, 0x49,
	0x6c, 0x60, 0x87, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xf5, 0x68, 0x72, 0xab, 0x00,
	0x00, 0x00,
}
